language: java
cache:
  directories:
  - "$HOME/.m2"
install:
- mvn test -Dgpg.skip=true
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $TRAVIS_BUILD_DIR/pubring.gpg.enc
  -out $TRAVIS_BUILD_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $TRAVIS_BUILD_DIR/secring.gpg.enc
  -out $TRAVIS_BUILD_DIR/secring.gpg -d
notifications:
  slack:
    secure: zTAAly6eNmmeIYUPy8fYq75rnFP8AZI9ambyNYFoKv2avQwPP/GitOcALXtxbPW8BfFYM5zcuPj9ddLZphL0Ve6fqWmyOG80OjGuyd1zMxcSVTTop0WM9JsEqbaDTgMH+0j30gtaEBdFTDqDkDQinTuYDJfonkC4IrP/fwH6hdnww2I8S9H0TUOeBoo7j5cJr4EJEJHdPTjxvvgjsbGQXStrUH/HG72UpwBXkoyAKHPyokOWmxH3JFQ0hV3wHsEHsGiNzfvnjVJnAt8u5RiAgAPIsfthwJHVDVPEPzseFAVPQUMNcgpJ/sc94EdbtlNopc7+B7ibF4Eo7cbILKSE4aduQe7pOF0Lg3mzNrVSSkIol4ysZNv9RECP3+NUab1S9LjnwEZaO1g8DZnBgEf6ME0wF+5axPRllerleZX0/wQt1TTDnPPXw/HsN6W0m+J1Uf+s9R5CZ0OR9gYOufahACXHmVUc0D906U7Jo1aYgE5jtXavgBnCbTiNHssDJ0bdP/HjILNeu+uwxWSbWBjhRwkmZlGZzYxKGU8koR4B0ROrUpqW6GGL2t2uzR/3S0fV95w2ZOoLqaZgmfAcKEhyqrNmb6har5qexHjcyIZIxT8Ph2mtl4K1l4ty2Japf4eQjCsTEfDXV1jByMfmqp6bD8Elt5DIqLX70Vxu9Slnj9Y=
